<div class="container">
    <div class="row">
        <div class="col-md-3">
            <form role="form" action="javascript:checkIn()" method="post">
                <div class="form-group">

                    <label for="exampleInputFio">
                        ФИО
                    </label>
                    <input type="text" class="form-control" name="fio" id="exampleInputFio" >
                </div>
                <div class="form-group">

                    <label for="exampleInputEmail">
                        Email
                    </label>
                    <input type="email" class="form-control" name="email" id="exampleInputEmail" >
                </div>
                <div class="form-group">

                    <label for="exampleInputRegion">
                        Область
                    </label>
                    <select id="exampleInputRegion" class="form-control" name="region">
                        <option></option>
                        <?php
                        foreach ($region as $item) {
                            echo '<option value="'. $item->getTerId() .'">'. $item->getTerName() .'</option>';
                        }
                        ?>
                    </select>
                </div>
                <div class="form-group" id="formCity" style="display: none">

                    <label for="exampleInputCity">
                        Город
                    </label>
                    <select id="exampleInputCity" class="form-control" name="city">
                        <option></option>
                    </select>
                </div>
                <div class="form-group" id="formDistrict" style="display: none;">

                    <label for="exampleInputDistrict">
                        Район
                    </label>
                    <select id="exampleInputDistrict" class="form-control" name="district">
                        <option></option>
                    </select>
                </div>

                <div id="message"></div>

                <button type="submit" class="btn btn-success">
                    Регистрация
                </button>
            </form>
        </div>
    </div>
</div>



<link rel="stylesheet" href="/chosen/docsupport/style.css">
<link rel="stylesheet" href="/chosen/docsupport/prism.css">
<link rel="stylesheet" href="/chosen/chosen.css">

<script src="/chosen/docsupport/jquery-3.2.1.min.js" type="text/javascript"></script>
<script src="/chosen/chosen.jquery.js" type="text/javascript"></script>
<script src="/chosen/docsupport/prism.js" type="text/javascript" charset="utf-8"></script>
<script src="/chosen/docsupport/init.js" type="text/javascript" charset="utf-8"></script>
